In [2]:
#import packages

import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#set directories for input and output

IN_DIR = "C:/Users/llschers/OneDrive - Indiana University/Documents/Kaggle/Competition Metadata"
OUT_DIR = "C:/Users/llschers/OneDrive - Indiana University/Documents/Kaggle/Filtered Competition Metadata"

In [4]:
#read in dfs and declare variables to select competition of interest

comps_df = pd.read_csv(IN_DIR+'/Competitions.csv', parse_dates=['DeadlineDate'])
#comps_df.shape

### This is the line I will change to our competition ###

comp_title = "HuBMAP - Hacking the Kidney"
comp_overview = comps_df[comps_df.Title==comp_title]
comp_id = comp_overview.iloc[0]['Id']
#comp_id
comp_forum_id = comp_overview.iloc[0]['ForumId']
comp_forum_id

995088.0

In [5]:
comp_overview

,Id,Slug,Title,Subtitle,HostSegmentTitle,ForumId,OrganizationId,CompetitionTypeId,HostName,EnabledDate,...,EnableSubmissionModelHashes,EnableSubmissionModelAttachments,RewardType,RewardQuantity,NumPrizes,UserRankMultiplier,CanQualifyTiers,TotalTeams,TotalCompetitors,TotalSubmissions
3926,22990,hubmap-kidney-segmentation,HuBMAP - Hacking the Kidney,Identify glomeruli in human kidney tissue images,Research,995088.0,3760.0,1,NaN,11/16/2020 22:11:08,...,False,False,USD,60000.0,3,1.0,True,1216,1646,35333

In [6]:
#write filtered competitions dataframe to csv
comp_overview.to_csv(OUT_DIR+'/Competitions.csv')

In [7]:
# filter and write Teams
teams_df = pd.read_csv(IN_DIR+'/Teams.csv', infer_datetime_format=True)

comp_teams_df = teams_df[teams_df.CompetitionId==comp_id].dropna(subset=['LastSubmissionDate'])

team_ids_list = comp_teams_df.Id.unique().tolist()
#len(team_ids_list)

comp_teams_df.to_csv(OUT_DIR+'/Teams.csv')

In [8]:
#filter forums, forumtopics, forumMessages, and forum Message Votes
forums_df = pd.read_csv(IN_DIR+'/Forums.csv', infer_datetime_format=True)
forums_topics_df = pd.read_csv(IN_DIR+'/ForumTopics.csv', infer_datetime_format=True)
forums_messages_df = pd.read_csv(IN_DIR+'/ForumMessages.csv', infer_datetime_format=True)
forums_message_votes_df = pd.read_csv(IN_DIR+'/ForumMessageVotes.csv', infer_datetime_format=True)

In [9]:
comp_forums_df = forums_df[forums_df.Id==comp_forum_id]
comp_forums_topics_df = forums_topics_df[forums_topics_df.ForumId==comp_forum_id]

#have to filter by forum topic
topic_ids = list(comp_forums_topics_df.Id.unique())
#topic_ids

comp_forums_messages_df = forums_messages_df[forums_messages_df.ForumTopicId.isin(topic_ids)]
#comp_forums_messages_df.head(5)

#have to filter by forum message
message_ids = list(comp_forums_messages_df.Id.unique())
comp_forums_message_votes_df = forums_message_votes_df[forums_message_votes_df.ForumMessageId.isin(message_ids)]
comp_forums_message_votes_df.head(5)

              Id  ForumMessageId  FromUserId  ToUserId    VoteDate
1224336  1626312         1081179     4178592   1095143  11/16/2020
1224337  1626447         1081179     5314639   1095143  11/17/2020
1224338  1626456         1081179     4878384   1095143  11/17/2020
1224339  1626600         1081179     1304450   1095143  11/17/2020
1224340  1626612         1081179     6172537   1095143  11/17/2020

In [10]:
comp_forums_messages_df.shape

(3053, 8)

In [11]:
comp_forums_df.to_csv(OUT_DIR+'/Forums.csv')
comp_forums_topics_df.to_csv(OUT_DIR+'/ForumTopics.csv')
comp_forums_messages_df.to_csv(OUT_DIR+'/ForumMessages.csv')
comp_forums_message_votes_df.to_csv(OUT_DIR+'/ForumMessageVotes.csv')

In [12]:
#Filter users by whether they are on a team in the competition or not
users_df = pd.read_csv(IN_DIR+'/Users.csv', infer_datetime_format=True)
#for this, I will also need the teammemberships info
team_memberships_df = pd.read_csv(IN_DIR+'/TeamMemberships.csv', infer_datetime_format=True)
team_memberships_df.shape

(4212248, 4)

In [13]:
comp_team_memberships_df = team_memberships_df[team_memberships_df.TeamId.isin(team_ids_list)]
comp_team_memberships_df.head(5)

              Id   TeamId   UserId RequestDate
3674752  5999962  5838851  3516796  11/16/2020
4052699  6000019  5838905  2116404  11/16/2020
4052700  6000041  5838923  3891191  11/16/2020
4052701  6000046  5838928   385905  11/16/2020
4052708  6000106  5838987   299834  11/16/2020

In [14]:
comp_users_list = list(comp_team_memberships_df.UserId.unique())
#comp_users_list
comp_users_df = users_df[users_df.Id.isin(comp_users_list)]
comp_users_df.to_csv(OUT_DIR+'/Users.csv')

In [15]:
kernelVersionCompSources_df = pd.read_csv(IN_DIR+'/KernelVersionCompetitionSources.csv', infer_datetime_format=True)

In [16]:
comp_kernelversionids_df = kernelVersionCompSources_df[kernelVersionCompSources_df.SourceCompetitionId==comp_id]
comp_kernelversionids_df.shape

(9632, 3)

In [17]:
comp_kernel_ids_list = comp_kernelversionids_df.KernelVersionId.unique()
len(comp_kernel_ids_list)

9632

In [18]:
kernels_df = pd.read_csv(IN_DIR+'/Kernels.csv', infer_datetime_format=True)
kernels_df.shape

(513204, 16)

In [19]:
comp_kernels_df = kernels_df[kernels_df.CurrentKernelVersionId.isin(comp_kernel_ids_list)]
#comp_kernels_df.shape (337,16)
comp_kernels_df.head()

,Id,AuthorUserId,CurrentKernelVersionId,ForkParentKernelVersionId,ForumTopicId,FirstKernelVersionId,CreationDate,EvaluationDate,MadePublicDate,IsProjectLanguageTemplate,CurrentUrlSlug,Medal,MedalAwardDate,TotalViews,TotalComments,TotalVotes
425092,12576357,5960060,47173731.0,NaN,197860.0,45768110.0,10/29/2020 16:57:34,11/18/2020,11/17/2020,False,dataset-details,2.0,12/04/2020,2505,11,43
428906,12731613,5960060,47248117.0,NaN,203357.0,46322403.0,11/06/2020 17:26:36,11/19/2020,11/17/2020,False,run-length-encoding,3.0,11/24/2020,1094,4,21
428908,12731684,5960060,47267562.0,NaN,NaN,46322696.0,11/06/2020 17:32:41,11/19/2020,11/17/2020,False,polygon-to-pixel-mask-conversion,3.0,11/20/2020,1177,0,18
428911,12731722,5960060,46511245.0,NaN,197847.0,46322853.0,11/06/2020 17:35:53,11/09/2020,11/17/2020,False,glomeruli-detection-related-works,2.0,01/08/2021,2236,1,38
432238,12882651,5760729,47512231.0,NaN,198534.0,46886425.0,11/14/2020 19:01:05,11/23/2020,11/17/2020,False,hubmap-looking-at-tfrecords,3.0,11/17/2020,1067,5,22

In [20]:
comp_kernels_df.to_csv(OUT_DIR+'/Kernels.csv')

In [21]:
comp_kernels_df.shape

(337, 16)

In [22]:
#filter datasets by forum id: 995088.0

datasets_df = pd.read_csv(IN_DIR+'/Datasets.csv')
datasets_df.shape #(91257, 16)
datasets_df.head()

C:\Users\llschers\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Id,CreatorUserId,OwnerUserId,OwnerOrganizationId,CurrentDatasetVersionId,CurrentDatasourceVersionId,ForumId,Type,CreationDate,ReviewDate,FeatureDate,LastActivityDate,TotalViews,TotalDownloads,TotalVotes,TotalKernels
0,9,1,NaN,4.0,2237907.0,2279744.0,794,2,09/08/2015 19:01:00,09/08/2015,NaN,02/05/2018,149490,5684,489,739
1,20,866896,NaN,373.0,4275.0,4275.0,999,2,01/13/2016 02:01:43,01/13/2016,NaN,02/06/2018,316876,45166,981,506
2,27,304806,304806.0,NaN,792993.0,814782.0,1115,2,03/09/2016 04:10:56,08/31/2016,NaN,02/05/2018,301310,54572,823,467
3,45,618787,618787.0,NaN,446.0,446.0,1292,2,05/20/2016 19:30:33,NaN,NaN,02/05/2018,45159,3826,72,79
4,52,304806,304806.0,NaN,799912.0,821830.0,1311,2,05/26/2016 03:21:22,05/26/2016,NaN,02/04/2018,28477,1575,92,19

In [23]:
comp_datasets_df = datasets_df[datasets_df.ForumId==int(comp_forum_id)]
comp_datasets_df.shape

(0, 16)

In [24]:
int(comp_forum_id)

995088

In [25]:
print(datasets_df.ForumId.unique())

[    794     999    1115 ... 1377430 1377623 1377641]

In [26]:
# troubleshooting kernal lineage network
kernels_df.head()

,Id,AuthorUserId,CurrentKernelVersionId,ForkParentKernelVersionId,ForumTopicId,FirstKernelVersionId,CreationDate,EvaluationDate,MadePublicDate,IsProjectLanguageTemplate,CurrentUrlSlug,Medal,MedalAwardDate,TotalViews,TotalComments,TotalVotes
0,1,2505,205.0,NaN,NaN,1.0,03/25/2015 18:25:32,03/23/2018,03/25/2015,False,hello,NaN,NaN,153,0,0
1,2,3716,1748.0,NaN,26670.0,2.0,03/25/2015 18:31:07,04/16/2015,03/25/2015,False,rf-proximity,3.0,07/15/2016,8515,1,13
2,4,3716,41.0,NaN,NaN,9.0,03/25/2015 21:57:36,03/23/2018,03/25/2015,False,r-version,NaN,NaN,90,0,0
3,5,28963,19.0,NaN,NaN,13.0,03/25/2015 22:01:04,03/23/2018,03/25/2015,False,test1,NaN,NaN,100,0,0
4,6,3716,21.0,NaN,NaN,15.0,03/25/2015 22:19:00,03/23/2018,03/25/2015,False,are-icons-missing,NaN,NaN,105,0,0

In [27]:
comp_kernels_df.head()

,Id,AuthorUserId,CurrentKernelVersionId,ForkParentKernelVersionId,ForumTopicId,FirstKernelVersionId,CreationDate,EvaluationDate,MadePublicDate,IsProjectLanguageTemplate,CurrentUrlSlug,Medal,MedalAwardDate,TotalViews,TotalComments,TotalVotes
425092,12576357,5960060,47173731.0,NaN,197860.0,45768110.0,10/29/2020 16:57:34,11/18/2020,11/17/2020,False,dataset-details,2.0,12/04/2020,2505,11,43
428906,12731613,5960060,47248117.0,NaN,203357.0,46322403.0,11/06/2020 17:26:36,11/19/2020,11/17/2020,False,run-length-encoding,3.0,11/24/2020,1094,4,21
428908,12731684,5960060,47267562.0,NaN,NaN,46322696.0,11/06/2020 17:32:41,11/19/2020,11/17/2020,False,polygon-to-pixel-mask-conversion,3.0,11/20/2020,1177,0,18
428911,12731722,5960060,46511245.0,NaN,197847.0,46322853.0,11/06/2020 17:35:53,11/09/2020,11/17/2020,False,glomeruli-detection-related-works,2.0,01/08/2021,2236,1,38
432238,12882651,5760729,47512231.0,NaN,198534.0,46886425.0,11/14/2020 19:01:05,11/23/2020,11/17/2020,False,hubmap-looking-at-tfrecords,3.0,11/17/2020,1067,5,22

In [28]:
target = comp_kernels_df[comp_kernels_df.CurrentUrlSlug=="unet-baseline-train"]
target

,Id,AuthorUserId,CurrentKernelVersionId,ForkParentKernelVersionId,ForumTopicId,FirstKernelVersionId,CreationDate,EvaluationDate,MadePublicDate,IsProjectLanguageTemplate,CurrentUrlSlug,Medal,MedalAwardDate,TotalViews,TotalComments,TotalVotes
433622,12947186,684758,47135465.0,47074200.0,197804.0,47130623.0,11/18/2020 03:29:08,11/18/2020,11/18/2020,False,unet-baseline-train,3.0,11/18/2020,778,3,14

In [29]:
target_parent = kernels_df[kernels_df.CurrentKernelVersionId==47074200]
target_parent

,Id,AuthorUserId,CurrentKernelVersionId,ForkParentKernelVersionId,ForumTopicId,FirstKernelVersionId,CreationDate,EvaluationDate,MadePublicDate,IsProjectLanguageTemplate,CurrentUrlSlug,Medal,MedalAwardDate,TotalViews,TotalComments,TotalVotes
433288,12930165,1094066,47074200.0,NaN,NaN,47065816.0,11/17/2020 08:28:26,11/17/2020,11/17/2020,False,hubmap-res34unet-baseline-train,2.0,11/29/2020,4414,0,29

In [30]:
#filter submissions
submissions_df = pd.read_csv(IN_DIR+'/Submissions.csv', infer_datetime_format=True)
submissions_df

C:\Users\llschers\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (8,10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Id,SubmittedUserId,TeamId,SourceKernelVersionId,SubmissionDate,ScoreDate,IsAfterDeadline,PublicScoreLeaderboardDisplay,PublicScoreFullPrecision,PrivateScoreLeaderboardDisplay,PrivateScoreFullPrecision
0,182472,46734.0,22634,NaN,09/07/2012,NaN,False,1.274671e+06,1.27467e+06,1.268454e+06,1.26845e+06
1,182476,46734.0,22634,NaN,09/07/2012,NaN,False,1.274671e+06,1.27467e+06,1.268454e+06,1.26845e+06
2,188080,46734.0,22634,NaN,09/22/2012,NaN,False,1.111674e+05,111167,9.397398e+04,93974
3,188086,46734.0,22634,NaN,09/22/2012,NaN,False,9.912841e+04,99128.4,1.040197e+05,104020
4,189378,46734.0,22634,NaN,09/24/2012,NaN,False,1.073273e+05,107327,1.170247e+05,117025
...,...,...,...,...,...,...,...,...,...,...,...
9988385,21083043,1753896.0,6667218,NaN,05/14/2021,05/14/2021,True,8.086000e-02,0.0808662,7.940000e-02,0.079408
9988386,21096463,1753896.0,6667218,NaN,05/15/2021,05/15/2021,True,4.550000e-02,0.0455044,4.592000e-02,0.0459298
9988387,21110294,1753896.0,6667218,NaN,05/16/2021,05/16/2021,True,7.817900e-01,0.781798,7.961900e-01,0.796194
9988388,21129556,6991733.0,6812467,NaN,05/17/2021,05/17/2021,True,7.420500e-01,0.74205,7.554300e-01,0.755433
9988389,21129058,6991733.0,6812467,NaN,05/17/2021,05/17/2021,True,8.092100e-01,0.809211,8.154500e-01,0.815459

In [32]:
comp_submissions_df = submissions_df[submissions_df.TeamId.isin(team_ids_list)]
comp_submissions_df

,Id,SubmittedUserId,TeamId,SourceKernelVersionId,SubmissionDate,ScoreDate,IsAfterDeadline,PublicScoreLeaderboardDisplay,PublicScoreFullPrecision,PrivateScoreLeaderboardDisplay,PrivateScoreFullPrecision
8638530,18315247,417337.0,5839111,47922915.0,11/27/2020,04/23/2021,False,0.0000,0,0.0000,0
8638531,18317512,417337.0,5839111,47931992.0,11/27/2020,04/23/2021,False,0.0000,0,0.0000,0
8638532,18318861,417337.0,5839111,47936346.0,11/27/2020,04/23/2021,False,0.0000,0,0.0000,0
8638533,18319175,417337.0,5839111,47939582.0,11/27/2020,04/23/2021,False,0.0000,0,0.0000,0
8638534,18316734,417337.0,5839111,47927791.0,11/27/2020,04/23/2021,False,0.0000,0,0.0000,0
...,...,...,...,...,...,...,...,...,...,...,...
9984314,21010804,7245560.0,6676955,62513569.0,05/10/2021,05/10/2021,False,0.9377,0.937745,0.9459,0.945956
9984315,21010806,7245560.0,6676955,62513754.0,05/10/2021,05/10/2021,False,0.9375,0.937549,0.9459,0.945912
9984316,21002183,7188841.0,6716664,62487814.0,05/10/2021,05/10/2021,False,0.8740,0.874095,0.0000,0
9984317,21002453,7188841.0,6716664,62489350.0,05/10/2021,05/10/2021,False,0.8785,0.878538,0.0000,0
9984318,21011347,7188841.0,6716664,62519600.0,05/10/2021,05/10/2021,False,0.8840,0.884099,0.0000,0

In [33]:
comp_submissions_df.to_csv(OUT_DIR+'/Submissions.csv')